//
// Generated file, do not edit! Created by opp_msgtool 6.1 from msgs/Obs.msg.
//

#ifndef __OBS_M_H
#define __OBS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataPkt;
class BCP;
class Burst;
class CoreStatus;
class EdgeStatus;
class PathReply;
class ParamUpdate;
// cplusplus {{
#include <string>
// }}

/**
 * Class generated from <tt>msgs/Obs.msg:37</tt> by opp_msgtool.
 * <pre>
 * packet DataPkt
 * {
 *     int svc;          // 0=voz,1=datos,2=video
 * }
 * </pre>
 */
class DataPkt : public ::omnetpp::cPacket
{
  protected:
    int svc = 0;

  private:
    void copy(const DataPkt& other);

  protected:
    bool operator==(const DataPkt&) = delete;

  public:
    DataPkt(const char *name=nullptr, short kind=0);
    DataPkt(const DataPkt& other);
    virtual ~DataPkt();
    DataPkt& operator=(const DataPkt& other);
    virtual DataPkt *dup() const override {return new DataPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSvc() const;
    virtual void setSvc(int svc);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPkt& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:41</tt> by opp_msgtool.
 * <pre>
 * packet BCP
 * {
 *     int burstId;
 *     int srcId;
 *     int dst;
 *     int ingressCore;
 *     int bytes;
 *     double offset;
 *     string srcName;
 * 
 *     int srcEdge;
 *     int dstEdge;
 * 
 *     int pathLen;
 *     int path[];
 *     int hopIndex;
 * }
 * </pre>
 */
class BCP : public ::omnetpp::cPacket
{
  protected:
    int burstId = 0;
    int srcId = 0;
    int dst = 0;
    int ingressCore = 0;
    int bytes = 0;
    double offset = 0;
    omnetpp::opp_string srcName;
    int srcEdge = 0;
    int dstEdge = 0;
    int pathLen = 0;
    int *path = nullptr;
    size_t path_arraysize = 0;
    int hopIndex = 0;

  private:
    void copy(const BCP& other);

  protected:
    bool operator==(const BCP&) = delete;

  public:
    BCP(const char *name=nullptr, short kind=0);
    BCP(const BCP& other);
    virtual ~BCP();
    BCP& operator=(const BCP& other);
    virtual BCP *dup() const override {return new BCP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDst() const;
    virtual void setDst(int dst);

    virtual int getIngressCore() const;
    virtual void setIngressCore(int ingressCore);

    virtual int getBytes() const;
    virtual void setBytes(int bytes);

    virtual double getOffset() const;
    virtual void setOffset(double offset);

    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * srcName);

    virtual int getSrcEdge() const;
    virtual void setSrcEdge(int srcEdge);

    virtual int getDstEdge() const;
    virtual void setDstEdge(int dstEdge);

    virtual int getPathLen() const;
    virtual void setPathLen(int pathLen);

    virtual void setPathArraySize(size_t size);
    virtual size_t getPathArraySize() const;
    virtual int getPath(size_t k) const;
    virtual void setPath(size_t k, int path);
    virtual void insertPath(size_t k, int path);
    [[deprecated]] void insertPath(int path) {appendPath(path);}
    virtual void appendPath(int path);
    virtual void erasePath(size_t k);

    virtual int getHopIndex() const;
    virtual void setHopIndex(int hopIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BCP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BCP& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:58</tt> by opp_msgtool.
 * <pre>
 * packet Burst
 * {
 *     int burstId;
 *     int srcId;
 *     int dst;
 *     int bytes;
 * 
 *     int nVoice;
 *     int nData;
 *     int nVideo;
 * 
 *     string srcName;
 * 
 *     int srcEdge;
 *     int dstEdge;
 * 
 *     int pathLen;
 *     int hopIndex;
 *     int path[];
 * 
 *     simtime_t creationTime;
 * }
 * </pre>
 */
class Burst : public ::omnetpp::cPacket
{
  protected:
    int burstId = 0;
    int srcId = 0;
    int dst = 0;
    int bytes = 0;
    int nVoice = 0;
    int nData = 0;
    int nVideo = 0;
    omnetpp::opp_string srcName;
    int srcEdge = 0;
    int dstEdge = 0;
    int pathLen = 0;
    int hopIndex = 0;
    int *path = nullptr;
    size_t path_arraysize = 0;
    omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const Burst& other);

  protected:
    bool operator==(const Burst&) = delete;

  public:
    Burst(const char *name=nullptr, short kind=0);
    Burst(const Burst& other);
    virtual ~Burst();
    Burst& operator=(const Burst& other);
    virtual Burst *dup() const override {return new Burst(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDst() const;
    virtual void setDst(int dst);

    virtual int getBytes() const;
    virtual void setBytes(int bytes);

    virtual int getNVoice() const;
    virtual void setNVoice(int nVoice);

    virtual int getNData() const;
    virtual void setNData(int nData);

    virtual int getNVideo() const;
    virtual void setNVideo(int nVideo);

    virtual const char * getSrcName() const;
    virtual void setSrcName(const char * srcName);

    virtual int getSrcEdge() const;
    virtual void setSrcEdge(int srcEdge);

    virtual int getDstEdge() const;
    virtual void setDstEdge(int dstEdge);

    virtual int getPathLen() const;
    virtual void setPathLen(int pathLen);

    virtual int getHopIndex() const;
    virtual void setHopIndex(int hopIndex);

    virtual void setPathArraySize(size_t size);
    virtual size_t getPathArraySize() const;
    virtual int getPath(size_t k) const;
    virtual void setPath(size_t k, int path);
    virtual void insertPath(size_t k, int path);
    [[deprecated]] void insertPath(int path) {appendPath(path);}
    virtual void appendPath(int path);
    virtual void erasePath(size_t k);

    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Burst& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Burst& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:80</tt> by opp_msgtool.
 * <pre>
 * message CoreStatus
 * {
 *     int coreId;
 *     int queuedBursts;
 *     double estDelay;
 * }
 * </pre>
 */
class CoreStatus : public ::omnetpp::cMessage
{
  protected:
    int coreId = 0;
    int queuedBursts = 0;
    double estDelay = 0;

  private:
    void copy(const CoreStatus& other);

  protected:
    bool operator==(const CoreStatus&) = delete;

  public:
    CoreStatus(const char *name=nullptr, short kind=0);
    CoreStatus(const CoreStatus& other);
    virtual ~CoreStatus();
    CoreStatus& operator=(const CoreStatus& other);
    virtual CoreStatus *dup() const override {return new CoreStatus(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getCoreId() const;
    virtual void setCoreId(int coreId);

    virtual int getQueuedBursts() const;
    virtual void setQueuedBursts(int queuedBursts);

    virtual double getEstDelay() const;
    virtual void setEstDelay(double estDelay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CoreStatus& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CoreStatus& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:86</tt> by opp_msgtool.
 * <pre>
 * message EdgeStatus
 * {
 *     int edgeId;
 *     int totalBuffered;
 *     int nVoice;
 *     int nData;
 *     int nVideo;
 * }
 * </pre>
 */
class EdgeStatus : public ::omnetpp::cMessage
{
  protected:
    int edgeId = 0;
    int totalBuffered = 0;
    int nVoice = 0;
    int nData = 0;
    int nVideo = 0;

  private:
    void copy(const EdgeStatus& other);

  protected:
    bool operator==(const EdgeStatus&) = delete;

  public:
    EdgeStatus(const char *name=nullptr, short kind=0);
    EdgeStatus(const EdgeStatus& other);
    virtual ~EdgeStatus();
    EdgeStatus& operator=(const EdgeStatus& other);
    virtual EdgeStatus *dup() const override {return new EdgeStatus(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getEdgeId() const;
    virtual void setEdgeId(int edgeId);

    virtual int getTotalBuffered() const;
    virtual void setTotalBuffered(int totalBuffered);

    virtual int getNVoice() const;
    virtual void setNVoice(int nVoice);

    virtual int getNData() const;
    virtual void setNData(int nData);

    virtual int getNVideo() const;
    virtual void setNVideo(int nVideo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EdgeStatus& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EdgeStatus& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:94</tt> by opp_msgtool.
 * <pre>
 * message PathReply
 * {
 *     int burstId;
 *     int srcEdge;
 *     int dstEdge;
 *     int pathLen;
 *     int path[];
 * }
 * 
 * //**
 * // * UPDATE de parámetros híbridos (TOTAL) hacia el Edge.
 *  //* El SDController lo envía por ctrlOutEdges[edgeId].
 *  //
 * </pre>
 */
class PathReply : public ::omnetpp::cMessage
{
  protected:
    int burstId = 0;
    int srcEdge = 0;
    int dstEdge = 0;
    int pathLen = 0;
    int *path = nullptr;
    size_t path_arraysize = 0;

  private:
    void copy(const PathReply& other);

  protected:
    bool operator==(const PathReply&) = delete;

  public:
    PathReply(const char *name=nullptr, short kind=0);
    PathReply(const PathReply& other);
    virtual ~PathReply();
    PathReply& operator=(const PathReply& other);
    virtual PathReply *dup() const override {return new PathReply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);

    virtual int getSrcEdge() const;
    virtual void setSrcEdge(int srcEdge);

    virtual int getDstEdge() const;
    virtual void setDstEdge(int dstEdge);

    virtual int getPathLen() const;
    virtual void setPathLen(int pathLen);

    virtual void setPathArraySize(size_t size);
    virtual size_t getPathArraySize() const;
    virtual int getPath(size_t k) const;
    virtual void setPath(size_t k, int path);
    virtual void insertPath(size_t k, int path);
    [[deprecated]] void insertPath(int path) {appendPath(path);}
    virtual void appendPath(int path);
    virtual void erasePath(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PathReply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PathReply& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>msgs/Obs.msg:106</tt> by opp_msgtool.
 * <pre>
 * message ParamUpdate
 * {
 *     int edgeId;
 *     int LmaxTotal;
 *     double TmaxTotal; // segundos
 * }
 * </pre>
 */
class ParamUpdate : public ::omnetpp::cMessage
{
  protected:
    int edgeId = 0;
    int LmaxTotal = 0;
    double TmaxTotal = 0;

  private:
    void copy(const ParamUpdate& other);

  protected:
    bool operator==(const ParamUpdate&) = delete;

  public:
    ParamUpdate(const char *name=nullptr, short kind=0);
    ParamUpdate(const ParamUpdate& other);
    virtual ~ParamUpdate();
    ParamUpdate& operator=(const ParamUpdate& other);
    virtual ParamUpdate *dup() const override {return new ParamUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getEdgeId() const;
    virtual void setEdgeId(int edgeId);

    virtual int getLmaxTotal() const;
    virtual void setLmaxTotal(int LmaxTotal);

    virtual double getTmaxTotal() const;
    virtual void setTmaxTotal(double TmaxTotal);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ParamUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ParamUpdate& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataPkt*>(ptr.get<cObject>()); }
template<> inline BCP *fromAnyPtr(any_ptr ptr) { return check_and_cast<BCP*>(ptr.get<cObject>()); }
template<> inline Burst *fromAnyPtr(any_ptr ptr) { return check_and_cast<Burst*>(ptr.get<cObject>()); }
template<> inline CoreStatus *fromAnyPtr(any_ptr ptr) { return check_and_cast<CoreStatus*>(ptr.get<cObject>()); }
template<> inline EdgeStatus *fromAnyPtr(any_ptr ptr) { return check_and_cast<EdgeStatus*>(ptr.get<cObject>()); }
template<> inline PathReply *fromAnyPtr(any_ptr ptr) { return check_and_cast<PathReply*>(ptr.get<cObject>()); }
template<> inline ParamUpdate *fromAnyPtr(any_ptr ptr) { return check_and_cast<ParamUpdate*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OBS_M_H

