//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/msgs/Obs.msg.
//

#ifndef __OBS_M_H
#define __OBS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DataPkt;
class BCP;
class Burst;
class BurstAck;
// cplusplus {{
#include <string>
// }}

/**
 * Class generated from <tt>src/msgs/Obs.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet DataPkt
 * {
 *     int svc;          // 0=voz,1=datos,2=video
 * }
 * </pre>
 */
class DataPkt : public ::omnetpp::cPacket
{
  protected:
    int svc = 0;

  private:
    void copy(const DataPkt& other);

  protected:
    bool operator==(const DataPkt&) = delete;

  public:
    DataPkt(const char *name=nullptr, short kind=0);
    DataPkt(const DataPkt& other);
    virtual ~DataPkt();
    DataPkt& operator=(const DataPkt& other);
    virtual DataPkt *dup() const override {return new DataPkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSvc() const;
    virtual void setSvc(int svc);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPkt& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/msgs/Obs.msg:9</tt> by opp_msgtool.
 * <pre>
 * packet BCP
 * {
 *     int burstId;
 *     int bytes;
 *     double offset;
 * 
 *     int srcEdge;
 *     int dstEdge;
 * 
 *     int pathLen;
 *     int path[];
 *     int hopIndex;
 * }
 * </pre>
 */
class BCP : public ::omnetpp::cPacket
{
  protected:
    int burstId = 0;
    int bytes = 0;
    double offset = 0;
    int srcEdge = 0;
    int dstEdge = 0;
    int pathLen = 0;
    int *path = nullptr;
    size_t path_arraysize = 0;
    int hopIndex = 0;

  private:
    void copy(const BCP& other);

  protected:
    bool operator==(const BCP&) = delete;

  public:
    BCP(const char *name=nullptr, short kind=0);
    BCP(const BCP& other);
    virtual ~BCP();
    BCP& operator=(const BCP& other);
    virtual BCP *dup() const override {return new BCP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);

    virtual int getBytes() const;
    virtual void setBytes(int bytes);

    virtual double getOffset() const;
    virtual void setOffset(double offset);

    virtual int getSrcEdge() const;
    virtual void setSrcEdge(int srcEdge);

    virtual int getDstEdge() const;
    virtual void setDstEdge(int dstEdge);

    virtual int getPathLen() const;
    virtual void setPathLen(int pathLen);

    virtual void setPathArraySize(size_t size);
    virtual size_t getPathArraySize() const;
    virtual int getPath(size_t k) const;
    virtual void setPath(size_t k, int path);
    virtual void insertPath(size_t k, int path);
    [[deprecated]] void insertPath(int path) {appendPath(path);}
    virtual void appendPath(int path);
    virtual void erasePath(size_t k);

    virtual int getHopIndex() const;
    virtual void setHopIndex(int hopIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BCP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BCP& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/msgs/Obs.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet Burst
 * {
 *     int burstId;
 *     int bytes;
 * 
 *     int srcEdge;
 *     int dstEdge;
 * 
 *     int svc;                // <-- NUEVO
 *     double assemblyTime;    // <-- NUEVO
 *     double sendTime;        // <-- NUEVO
 * 
 *     int nVoice;
 *     int nData;
 *     int nVideo;
 * }
 * </pre>
 */
class Burst : public ::omnetpp::cPacket
{
  protected:
    int burstId = 0;
    int bytes = 0;
    int srcEdge = 0;
    int dstEdge = 0;
    int svc = 0;
    double assemblyTime = 0;
    double sendTime = 0;
    int nVoice = 0;
    int nData = 0;
    int nVideo = 0;

  private:
    void copy(const Burst& other);

  protected:
    bool operator==(const Burst&) = delete;

  public:
    Burst(const char *name=nullptr, short kind=0);
    Burst(const Burst& other);
    virtual ~Burst();
    Burst& operator=(const Burst& other);
    virtual Burst *dup() const override {return new Burst(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);

    virtual int getBytes() const;
    virtual void setBytes(int bytes);

    virtual int getSrcEdge() const;
    virtual void setSrcEdge(int srcEdge);

    virtual int getDstEdge() const;
    virtual void setDstEdge(int dstEdge);

    virtual int getSvc() const;
    virtual void setSvc(int svc);

    virtual double getAssemblyTime() const;
    virtual void setAssemblyTime(double assemblyTime);

    virtual double getSendTime() const;
    virtual void setSendTime(double sendTime);

    virtual int getNVoice() const;
    virtual void setNVoice(int nVoice);

    virtual int getNData() const;
    virtual void setNData(int nData);

    virtual int getNVideo() const;
    virtual void setNVideo(int nVideo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Burst& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Burst& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/msgs/Obs.msg:38</tt> by opp_msgtool.
 * <pre>
 * message BurstAck
 * {
 *     int burstId;
 * }
 * </pre>
 */
class BurstAck : public ::omnetpp::cMessage
{
  protected:
    int burstId = 0;

  private:
    void copy(const BurstAck& other);

  protected:
    bool operator==(const BurstAck&) = delete;

  public:
    BurstAck(const char *name=nullptr, short kind=0);
    BurstAck(const BurstAck& other);
    virtual ~BurstAck();
    BurstAck& operator=(const BurstAck& other);
    virtual BurstAck *dup() const override {return new BurstAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BurstAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BurstAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DataPkt *fromAnyPtr(any_ptr ptr) { return check_and_cast<DataPkt*>(ptr.get<cObject>()); }
template<> inline BCP *fromAnyPtr(any_ptr ptr) { return check_and_cast<BCP*>(ptr.get<cObject>()); }
template<> inline Burst *fromAnyPtr(any_ptr ptr) { return check_and_cast<Burst*>(ptr.get<cObject>()); }
template<> inline BurstAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<BurstAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OBS_M_H

